# Generated by Django 6.0.1 on 2026-02-09 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='image',
            field=models.ImageField(blank=True, upload_to='users_images'),
        ),
        migrations.AddField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('doctor', 'Доктор'), ('patient', 'Пользователь')], default='patient', max_length=20, verbose_name='Роль'),
        ),
    ]
