# Generated by Django 6.0.1 on 2026-02-13 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_users_email_alter_users_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='image',
            field=models.ImageField(blank=True, upload_to='users_images/'),
        ),
    ]
