# Generated by Django 6.0.1 on 2026-02-14 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('status', models.CharField(choices=[('confirmed', 'Подтверджена'), ('paid', 'Оплачен'), ('started', 'Начата'), ('awaiting', 'Ожидается'), ('completed', 'Завершена')], default='awaiting')),
                ('started_at', models.DateTimeField(verbose_name='Начало приема')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Конец приема')),
            ],
        ),
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('legal_address', models.CharField(blank=True, max_length=255)),
                ('physical_address', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
