# Generated by Django 6.0.1 on 2026-02-09 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='appointment',
            new_name='appointment_doctor__7bf40a_idx',
            old_name='appointment_appoin_doctor__83f254_idx',
        ),
        migrations.RenameIndex(
            model_name='clinic',
            new_name='appointment_name_04eef8_idx',
            old_name='appointment_clinic_name_4ae83f_idx',
        ),
        migrations.RenameIndex(
            model_name='doctor',
            new_name='appointment_clinic__8e6065_idx',
            old_name='appointment_doctor_clinic__cb3c90_idx',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Конец приема'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='started_at',
            field=models.DateTimeField(default='2024-01-01 12:00', verbose_name='Начало приема'),
            preserve_default=False,
        ),
    ]
