# Generated by Django 6.0.1 on 2026-02-14 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_appointments', to=settings.AUTH_USER_MODEL, verbose_name='Пациент'),
        ),
        migrations.AddIndex(
            model_name='clinic',
            index=models.Index(fields=['name'], name='appointment_name_04eef8_idx'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_appointments', to='appointment.clinic', verbose_name='Клиника'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='clinic',
            field=models.ManyToManyField(related_name='doctors', to='appointment.clinic'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='doctor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='appointment.doctor', verbose_name='Доктор'),
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['doctor', 'specialization'], name='appointment_doctor__fbf108_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['doctor', 'created_at', 'status'], name='appointment_doctor__7bf40a_idx'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.CheckConstraint(condition=models.Q(('ended_at__gt', models.F('started_at'))), name='ended_time_gt_started_time'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(fields=('doctor', 'started_at'), name='unique_doctor_started_at_time'),
        ),
    ]
