# Generated by Django 6.0.1 on 2026-02-13 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_rename_appointment_appoin_doctor__83f254_idx_appointment_doctor__7bf40a_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Подтверджена'), ('paid', 'Оплачен'), ('started', 'Начата'), ('awaiting', 'Ожидается'), ('completed', 'Завершена')], default='awaiting'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='doctor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
