# Generated by Django 6.0.1 on 2026-02-16 15:46

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
from django.conf import settings
from django.db import migrations, models
from django.contrib.postgres.operations import BtreeGistExtension


class Migration(migrations.Migration):
    dependencies = [
        ("appointment", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        BtreeGistExtension(),
        migrations.RemoveConstraint(
            model_name="appointment",
            name="ended_time_gt_started_time",
        ),
        migrations.RemoveConstraint(
            model_name="appointment",
            name="unique_doctor_started_at_time",
        ),
        migrations.AddField(
            model_name="appointment",
            name="timestamp",
            field=django.contrib.postgres.fields.ranges.DateTimeRangeField(
                blank=True, null=True
            ),
        ),
        migrations.AddConstraint(
            model_name="appointment",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                condition=models.Q(
                    ("status__in", ["paid", "awaiting", "confirmed", "started"])
                ),
                expressions=[("timestamp", "&&"), ("doctor", "=")],
                name="unique_timestamp_for_doctor_appointment",
            ),
        ),
        migrations.AddConstraint(
            model_name="appointment",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                condition=models.Q(
                    ("status__in", ["awaiting", "started", "paid", "confirmed"])
                ),
                expressions=[("timestamp", "&&"), ("patient", "=")],
                name="unique_timestamp_for_patient",
            ),
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="ended_at",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="started_at",
        ),
    ]
