# Generated by Django 6.0.1 on 2026-02-20 20:37

import datetime
import django.contrib.postgres.fields.ranges
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_remove_appointment_ended_time_gt_started_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='timestamp',
            field=django.contrib.postgres.fields.ranges.DateTimeRangeField(default=(datetime.datetime(2026, 2, 20, 20, 37, 43, 12046, tzinfo=datetime.timezone.utc), datetime.datetime(2026, 2, 20, 21, 37, 43, 12046, tzinfo=datetime.timezone.utc))),
            preserve_default=False,
        ),
    ]
